---
# tasks file for auth
- name: Create the auth user
  ansible.builtin.user:
    name: "{{ app.user}}"
- name: Create the app directory and apply the necessary permissions
  ansible.builtin.file:
    path: "{{ app.directory }}"
    state: directory
    owner: "{{ app.user}}"
    group: "{{ app.group}}"
    mode: "0700"
    recurse: true
- name: Clone the weatherapp repo
  ansible.builtin.git:
    repo: https://gitlab.com/abohmeed/moderndevops-weatherapp.git
    dest: "{{ repo_directory }}"
    single_branch: yes
    version: main
- name: Build and deploy the auth service
  ansible.builtin.shell:
    cmd: "{{ ansible_local.golang.general.home }}/bin/go get -v ./... && {{ ansible_local.golang.general.home }}/bin/go build -o {{ app.directory }} -v ./..."
    chdir: "{{ repo_directory }}/auth/src/main"
  notify: Apply the necessary ownership and permissions
- name: Get the database hostname
  set_fact:
    db_hostname: "{{ lookup('aws_ssm',ssm.db_host).split(':').0 }}"
- name: Get the database username
  set_fact:
    db_username: "{{ lookup('aws_ssm',ssm.db_admin) }}"
- name: Get the database password
  set_fact:
    db_password: "{{ lookup('aws_ssm',ssm.db_password) }}"
- name: Install MySQL client
  apt:
    name: mysql-client
    state: latest
- name: Deploy the SQL file for user creation
  ansible.builtin.template:
    src: user.sql.j2
    dest: "{{ app.directory }}/user.sql"
    owner: "{{ app.user}}"
    group: "{{ app.group}}"
    mode: "0400"
- name: Create the app DB user
  shell:
    cmd: "mysql -h {{db_hostname}} -u {{db_username}} -p{{db_password}} < {{ app.directory }}/user.sql && rm -f {{ app.directory }}/user.sql"
  no_log: true
- name: Create the auth systemd service
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/auth.service
    owner: root
    group: root
  notify: Start the auth service
